apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/cuttlefacts
# SINGLE FILES
  - ./cuttlefacts-services.yaml
# USED AS DEPLOY PACTH
patchesStrategicMerge:
  - ./podinfo-values.yaml